### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by jwillemsen**
Keeps the used github actions up to date

### CODE REVIEW

**Comment by opatry** [comment]
Sorry @jwillemsen , I totally missed the notification about this!!
Meld in the middle of other dependabot alerts for Bundler most likely.

I wasn't aware of such possibility which sounds nice.
I'll complete it with explicit checks for Bundler & npm.

**Comment by opatry** [comment]
Done in 39459444703b86773556a38578096b9ca2275ba0

**Comment by opatry** [comment]
@jwillemsen many thanks again for this! I applied the same on another (private) repository with much more activity (and dependencies!) and it raised quite a lot of updates 😝 

I used to rely on built-in GitHub dependabot alerts (which is already quite nice) but much better with this approach.

🙇

**Comment by jwillemsen** [comment]
No problem, as far as I remember I encountered this repo when working on a nanoc upgrade. We are also using dependabot for a lot of repositories this way, works great.

**Pull request merged**
